services:
  postgres:
    image: postgres:16-alpine
    container_name: fintrack-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fintrack
    ports:
      - "5433:5432"
    volumes:
      - fintrack-pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d fintrack"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  fintrack-pgdata:
