DROP POLICY IF EXISTS "user owns user_profiles" ON user_profiles;
DROP POLICY IF EXISTS "user owns budget_plans" ON budget_plans;
DROP POLICY IF EXISTS "user owns budget_items via plan" ON budget_items;
DROP POLICY IF EXISTS "user owns transactions" ON transactions;
DROP POLICY IF EXISTS "user owns debt_items" ON debt_items;
DROP POLICY IF EXISTS "user owns goals" ON goals;
DROP POLICY IF EXISTS "user owns weekly_reports" ON weekly_reports;
DROP POLICY IF EXISTS "user owns api_tokens" ON api_tokens;
DROP POLICY IF EXISTS "user reads system + own categories" ON expense_categories;
DROP POLICY IF EXISTS "user inserts own categories" ON expense_categories;
DROP POLICY IF EXISTS "user updates own categories" ON expense_categories;
DROP POLICY IF EXISTS "user deletes own categories" ON expense_categories;
ALTER TABLE user_profiles      DISABLE ROW LEVEL SECURITY;
ALTER TABLE expense_categories DISABLE ROW LEVEL SECURITY;
ALTER TABLE budget_plans       DISABLE ROW LEVEL SECURITY;
ALTER TABLE budget_items       DISABLE ROW LEVEL SECURITY;
ALTER TABLE transactions       DISABLE ROW LEVEL SECURITY;
ALTER TABLE debt_items         DISABLE ROW LEVEL SECURITY;
ALTER TABLE goals              DISABLE ROW LEVEL SECURITY;
ALTER TABLE weekly_reports     DISABLE ROW LEVEL SECURITY;
ALTER TABLE api_tokens         DISABLE ROW LEVEL SECURITY;
